# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-03-26 22:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logreg', '0002_remove_user_location'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='title',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='username',
            new_name='ip',
        ),
    ]
